import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import header from "./components/homePage";
import Header from "./components/header";
import Navbar from "./components/homePage";
import Session from "./components/session";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital Banking ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <footer/>
        {children}
        
        
        <Header/>
      </body>
    </html>
  );
}
